### PR TITLE
WEB-556: Remove Teacher dashboard tab.

### PR DESCRIPTION
**Pull request by polesye**
**Ticket:** [WEB-556](https://liv-it.atlassian.net/browse/WEB-556)

Remove Teacher dashboard tab. We're going to use lti version of the dashboard.
Will be merged after changes in Master Course.

@leha2000  @TamoshaytisV please review.

### CODE REVIEW

**Comment by TamoshaytisV** [comment]
positive-cat-meme-generator-it-s-ok-098ac2

**Comment by leha2000** [comment]
:+1:

**Comment by TamoshaytisV** [comment]
@polesye what's it waiting for?

**Comment by polesye** [comment]
@TamoshaytisV all comments you can find in the ticket.

**Pull request merged**
