### PR TITLE
WEB-2028: Fix login failed message

### PR DESCRIPTION
**Pull request by lukyfebrianto**
**JIRA:** https://liv-it.atlassian.net/browse/WEB-2028

**Merge deadline:** 20/09/2017

**Documentation:** https://liv-it.atlassian.net/wiki/spaces/UP/pages/104693761/Region+Configuration

**Reviewers:**
- [x] tag reviewer
- [x] tag reviewer

**Merge checklist:**
- [x] All reviewers approved
- [x] CI build is green
- [x] Documentation updated (not only docstrings)
- [x] Commits are squashed

**Post merge:**
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant
solutions, hacks, quick-and-dirty implementations, concerns about
migrations, etc.

### CODE REVIEW

**Comment by lukyfebrianto** [comment]
Update message and add region_code in the REGIONS configuration:
Example
```json
"{\"REGIONS\": {\"GB\": {\"name\": \"the United Kingdom\", \"login_url\": \"https://staging-courses-uk.labster.com/dashboard\", \"region_code\":\"UK\"}}}"
```
FYI: @polesye , @TamoshaytisV

**Comment by polesye** [comment]
@lukyfebrianto could you create a wiki page that describes how it can be configured, data format and how each key is used?

**Comment by polesye** [comment]
@lukyfebrianto why all Items in the checklist are marked as done? Is it possible to have PR with the branch that has been alrady deleted? Do we have any documentation about this? What is the page A in `Testing instructions:`, do we need this section in this PR? Could you cleanup the description?

**Comment by lukyfebrianto** [comment]
> @lukyfebrianto could you create a wiki page that describes how it can be configured, data format and how each key is used?

Document created: https://liv-it.atlassian.net/wiki/spaces/UP/pages/104693761/Region+Configuration

> Is it possible to have PR with the branch that has been alrady deleted? 

I think is possible because I ever do it before or should I recreate PR with another branch ? 

> What is the page A in Testing instructions:, do we need this section in this PR

I think we don't need to test it again because it's just little changed on message.

**Comment by polesye** [comment]
@lukyfebrianto great documentation. Good job!

**Review by polesye — APPROVED** [review]

**Review by TamoshaytisV — APPROVED** [review]

**Pull request merged**
