### PR TITLE
Remove unused TD code.

### PR DESCRIPTION
**Pull request by polesye**
Removes unsed TD code .

@leha2000 @TamoshaytisV please review.

### CODE REVIEW

**Comment by leha2000** [comment]
Did you just remove `lms/static/teacher_dashboard` folder and `lms/templates/teacher_dashboard/dashboard.html` file?

**Comment by polesye** [comment]
> Did you just remove lms/static/teacher_dashboard folder and lms/templates/teacher_dashboard/dashboard.html file?

@leha2000 yes, we removed TD from edX.

**Comment by leha2000** [comment]
:+1:

**Comment by polesye** [comment]
@avkoval please review.

**Comment by avkoval** [comment]
:+1:

**Pull request merged**
