### PR TITLE
TESLA-371: Remove the text "Instructor View" from EdX courses

### PR DESCRIPTION
**Pull request by lukyfebrianto**
**Description:** Remove the text "Instructor View" from EdX courses

**JIRA:** https://liv-it.atlassian.net/browse/TESLA-371

**Merge deadline:** List merge deadline (if any)

**Configuration instructions:** List any non-trivial configuration
instructions (if any).

**Testing instructions:**

1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.

**Reviewers:**
- [ ] tag reviewer
- [ ] tag reviewer

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant
solutions, hacks, quick-and-dirty implementations, concerns about
migrations, etc.

### CODE REVIEW

**Comment by lukyfebrianto** [comment]
Result:
Screenshot from 2019-06-18 14-27-58

**Comment by polesye** [comment]
@lukyfebrianto is it a bug in edX itself?

**Comment by lukyfebrianto** [comment]
@polesye actually this isn't bug from Edx, `Instructor View` that CS mentions is a name from course in our Edx so If CS want to remove it we need to remove it from template.

**Comment by polesye** [comment]
@lukyfebrianto does it make sense to display CCX course name instead?

**Comment by lukyfebrianto** [comment]
> @lukyfebrianto does it make sense to display CCX course name instead?

Yes, that makes sense.
changed, please check it. 
Thanks

**Comment by lukyfebrianto** [comment]
Preview:
Screenshot from 2019-06-19 11-15-27

**Review by polesye — APPROVED** [review]

**Review by madyasiwi — APPROVED** [review]

**Pull request merged**
