### PR TITLE
WEB-2884: An invalid link message is appeared if the password does not follow password policy.

### PR DESCRIPTION
**Pull request by lukyfebrianto**
**Description:**
User will get 2 error messages if the password entered does not follow password policy i.e.1. Error Resetting Password (either password is not complex or invalid length)2. Invalid Password Reset Link

The link is a valid one and after I received that error, I go back to previous page and enter the correct password, I can go through the password reset successfully.

**JIRA:** https://liv-it.atlassian.net/browse/WEB-2884

**Merge deadline:** List merge deadline (if any)

**Configuration instructions:** List any non-trivial configuration
instructions (if any).

**Testing instructions:**

1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.

**Reviewers:**
- [ ] tag reviewer
- [ ] tag reviewer

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant
solutions, hacks, quick-and-dirty implementations, concerns about
migrations, etc.

### CODE REVIEW

**Comment by TamoshaytisV** [comment]
@lukyfebrianto have you considered just adding recommended password structure info and validation on the reset password page?

**Comment by lukyfebrianto** [comment]
@TamoshaytisV  Yes, I already think about this solution but the problem is when there's some changes on our Pasword Policy in the settings (https://github.com/Livit/Livit.Learn.EdX/blob/labster/develop/lms/envs/labster.py#L67) it also needed to be changed.

**Comment by TamoshaytisV** [comment]
@lukyfebrianto can we just use those settings values in validation message? Like
`Password strengths does not meet minimal requirements: 1 number 1 capital char`
smth like that

**Review by TamoshaytisV — APPROVED** [review]

**Comment by TamoshaytisV** [comment]
@lukyfebrianto i think it's ok to go with your solution

**Review by madyasiwi — APPROVED** [review]

**Pull request merged**
