### PR TITLE
WEB-2513: Unable to add new coach via Edx

### PR DESCRIPTION
**Pull request by lukyfebrianto**
**Description:** 
 Unable to add new coach via Edx

**JIRA:** https://liv-it.atlassian.net/browse/WEB-2513

**Merge deadline:** List merge deadline (if any)

**Configuration instructions:** List any non-trivial configuration
instructions (if any).

**Testing instructions:**

1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.

**Reviewers:**
- [ ] tag reviewer
- [ ] tag reviewer

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant
solutions, hacks, quick-and-dirty implementations, concerns about
migrations, etc.

### CODE REVIEW

**Comment by polesye** [comment]
@lukyfebrianto please explain your solution

**Comment by lukyfebrianto** [comment]
> @lukyfebrianto please explain your solution

why is this happening?
because we only handle for ccx course not a master course that's why when we try to get id of ccx it goes error  https://github.com/Livit/Livit.Learn.EdX/pull/107/files#diff-b289cefe1d85995559153339637dc4bbR90.

solution:
Add a checker to check whether the course is ccx course, if yes execute the code
https://github.com/Livit/Livit.Learn.EdX/pull/107/files#diff-b289cefe1d85995559153339637dc4bbR88

fyi @polesye

**Review by polesye — APPROVED** [review]

**Comment by TamoshaytisV** [comment]
@lukyfebrianto @polesye is this issue related to some previous labster changes? How it worked previously?

**Comment by lukyfebrianto** [comment]
yes @TamoshaytisV,  previously  it working fine for ccx but if we want to add ccx_coach to master course it goes error that's why we trying to fix it.

**Review by TamoshaytisV — APPROVED** [review]

**Pull request merged**
